---
apiVersion: v1
kind: Pod
metadata:
  name: rss-site-1
  namespace: istio-system
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: nginx
      ports:
        - containerPort: 80
